### ISSUE TITLE
Use IHttpClientFactory instead of newing up httpclient

### ISSUE THREAD

**Issue by marty-shields** [TheAnachronism/StarCitizenAPIWrapper#11]
It is better to take advantage of .Net Cores IHttpClientFactory instead of newing up a new httpclient each time for the following reasons

- Newing up new instances each time of HttpClient can cause performance issues

 .NET Core has middleware which deals with all of this so you do not need to worry (IHttpClientFactory) : https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1

Using this has its advantages such as having one instance of the client running meaning better scale and performance, being able to inject in logging and retry policies etc

**Comment by TheAnachronism** [comment]
I have a bit of experience with the DI of .net core and the service collection. I'm just wondering, how I can use that in a class library.

**Comment by marty-shields** [comment]
Thats a good question that may need a bit of investigation. I believe this would be a case of requiring the caller of your library to be able to set this up (which they should be able to). So you would not setup the DI in your library itself (since that means you restrict people having to use a specific solution for DI) but instead pass through the factory into your constructor and put in the readme on how a calling client would set this up.

Another option is to maybe add to this by extending the service collection like so: https://mcguirev10.com/2018/01/31/net-core-class-library-dependency-injection.html#extending-iservicecollection

**Comment by marty-shields** [comment]
We could use the IServiceProvider as well: https://docs.microsoft.com/en-us/dotnet/api/system.iserviceprovider?view=netcore-3.1

**Comment by marty-shields** [comment]
Personally, I would personally leave it to the person calling the code to setup their dependancy needs, adding documentation what dependancies would need to be resolved. This keeps the library simple allowing the caller to do what they want with their dependancies

**Comment by TheAnachronism** [comment]
Wouldn't an extension method on the ServiceCollection do the job?
Like builder.services.AddStarCitizenAPIClient() or something?

**Comment by marty-shields** [comment]
Yes thats one posibility and may tend to your own needs just nicely. This one may be better when you have custom classes which need specific DI needs. For IHttpClientFactory (only being the single one at the moment) this would depend upon the caller themselves how they want to set the http client up

**Comment by TheAnachronism** [comment]
Exactly
I guess in this extension method, we'll just add the StarCitizenAPIClient. Now in what scope? Singleton, Transient?

**Comment by marty-shields** [comment]
This makes it specific how to create it: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1

`public class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public IConfiguration Configuration { get; }

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddHttpClient();
        // Remaining code deleted for brevity.`

**Comment by TheAnachronism** [comment]
Yes but the question is, if we want to add the StarCitizenAPI client class ALSO as a service.

**Comment by marty-shields** [comment]
If that's the case you could do that. 

Another thing to mention (not strictly related) is that the client itself is quite tightly coupled. Which would make it hard to make changes/additions without effecting other parts. It may be better to separate out the api code you have from your service logic to make it easier to test, maintain and fix. 

If I am being a bit over the top just let me know, I have quite a bit of experience working for a software consultancy and now a large tech company in the U.K. I'm not sure what your background is in and if development is something you are pursuing but these are some of the fundamentals we follow which help on big projects with big teams

**Comment by TheAnachronism** [comment]
yeah I'll have a look at how I could further separate some things.
About your other point. PLEASE give as much as advice as possible. I'm currently a student learning software development and doing a few projects on the side (like this one) so help from an actual developer is perfect :D

**Comment by TheAnachronism** [comment]
I'm currently trying out, if I can rewrite this thing for the ServiceCollection. The problem I have right now, is that I somehow have to pass the API-Key to the star-citizen client. I was thinking of adding another service, like a config service or something, in which I can just pass the api key to store it there once I need it.

**Comment by marty-shields** [comment]
> I'm currently trying out, if I can rewrite this thing for the ServiceCollection. The problem I have right now, is that I somehow have to pass the API-Key to the star-citizen client. I was thinking of adding another service, like a config service or something, in which I can just pass the api key to store it there once I need it.

I believe the library would have natural access to the callers config, having a dedicated config would be good with validation to ensure config is valid on run

**Comment by TheAnachronism** [comment]
That is true. E.g in ASP.NET Core you get access to IConfiguration everywhere so...

**Comment by marty-shields** [comment]
> That is true. E.g in ASP.NET Core you get access to IConfiguration everywhere so...
> 
> 
> 
> If you have a look at this new [feature branch](/TheAnachronism/StarCitizenAPIWrapper/tree/feature/ServiceCollection-Extension) I just created and tried a bit around.
> 
> I think that goes into the right direction.

Sure will be happy to later tonight or tomorrow.

**Comment by marty-shields** [comment]
I took a look a little late last night, I like what you have done however I wouldn't new up the client in startup and instead just pass through the IHttpClientFactory, you can then get the client through a method and do the requests.

Personally I think it would be better to handle the http request separately to your client and injecting in this new IHttpService into it instead. I will create a branch and let you know which one so you can take a look. This would mean we are abstracting away the http call from your actual logic which is in your client

**Comment by TheAnachronism** [comment]
Ah ok.
I just didn't think it would be necessary to strip away the http request, because its mostly just two lines.

**Comment by marty-shields** [comment]
In a way you are right, however it tightly couples the code and does not give abstraction, makes it harder to test etc. 

For example if you wanted to unit test your methods you would find it difficult to do without actually calling something with the client. Using an interface allows you to "mock" the client to return whatever you want making your testing more focused on only the logic you make

**Comment by TheAnachronism** [comment]
Ok yeah that makes sense. So you're working on an example?

**Comment by marty-shields** [comment]
yep looking now

**Comment by marty-shields** [comment]
Ok, I have made a branch which you can access here: https://github.com/marty-shields/StarCitizenAPIWrapper/tree/httpclient-refactor

If you clone this branch and take a look you will see I have made a number of changes which helps with the DI, abstraction, security and testability of the code. Let me know what you think and if you have any questions ill be happy to answer.

I have seperated out the http client requests to their own class and injected them into the client and then created an interface for the client as well which has access to the methods required. Access has been considered to only expose what is required (hence the internal access for some classes) which requires end users to interact with the interface meaning abstraction is done for the end user.

I'm a little busy for rest of today however if you give me a bit of time tomorrow I can add some unit testing in there as a start for yourself to learn from and be able to continue with. If you are happy with the changes let me know and ill create a pull request and we can get it merged in. I know there has been some substancial changes so don't be afraid to ask if theres anything you are unsure about

**Comment by TheAnachronism** [comment]
Ok so I'll just list the questions I have here and maybe edit this comment later on, if further questions should come up:
- Why did you use TryAddTransient in the ServiceCollectionExtensions?

**Comment by marty-shields** [comment]
> Ok so I'll just list the questions I have here and maybe edit this comment later on, if further questions should come up:
> 
> - Why did you use TryAddTransient in the ServiceCollectionExtensions?

That was a mistake. TryAdd will only add if it's not there already, I just need to use AddTransient instead. I initially added to try test something specific and forgot to change back

**Comment by marty-shields** [comment]
> Ok so I'll just list the questions I have here and maybe edit this comment later on, if further questions should come up:
> 
> - Why did you use TryAddTransient in the ServiceCollectionExtensions?
> 
> Ok so I went through the whole thing and I understand why you did those abstractions. I guess I'm just not experienced enough yet, when to use interfaces for such things and when not.
> 
> A general rule would be, to write such services as an interface I guess?
> 
> 
> 
> Otherwise I'm fine with those changes. You can create the PR.
> 
> Also I guess with all those changes we made the next release would be 3.0.0 or something...

A normal rule of thumb I normally go by is if there is actual logic or functionality that you have you would want to abstract it somehow either through an abstract class or an interface. The only time I would not abstract a class would be if it was a model with no functionality or logic or something which is concrete in itself like a static class as an example.

So typically yes services, repositories, clients, helpers (if not static or specific) would be abstracted. We want to aim for as much abstraction as possible to help with maintainability / testability. If we have an interface which specifies a contract and need to change the underlying code, nothing calling that interface has to worry as it implies its behaviour from the contract and not the implementation. We can switch out the class implementing the same interface.

I will add some tests, and send over a PR tomorrow

**Comment by TheAnachronism** [comment]
So I guess we can close this?

**Comment by marty-shields** [comment]
Yep. Hopefully there's some things you can take from this and learn from

**Comment by TheAnachronism** [comment]
With the PR from @marty-shields merged we can close this issue.
