### ISSUE TITLE
New project layout proposal

### ISSUE THREAD

**Issue by marty-shields** [TheAnachronism/StarCitizenAPIWrapper#8]
As discussed in the redit post I described that it may be more beneficial to restructure the project to make it easier to navigate. How I propose to do this is to do the following:

1. In root have a folder src for source files, test for test files and examples for examples

**Comment by marty-shields** [comment]
I am more than happy to do this so you can see what it would look like if you wish?

**Comment by TheAnachronism** [comment]
Sure go on. Like I said in README.md create a PR and I'll have a look at it.
